// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrpp1G9sgSjz0XPFgv8zk__PRjHCzMFmw',
    appId: '1:90703966559:android:e90571d956ba31d8af06ea',
    messagingSenderId: '90703966559',
    projectId: 'acutetriage-app',
    storageBucket: 'acutetriage-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd4m1EXg7OwDthzhr8yqm6SfPwsaUtSvM',
    appId: '1:90703966559:ios:2c14e362e8c2f125af06ea',
    messagingSenderId: '90703966559',
    projectId: 'acutetriage-app',
    storageBucket: 'acutetriage-app.appspot.com',
    iosBundleId: 'dk.acutetriage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcUjlubxHfjmAUT4o3fekghSeY3ZkqUaA',
    appId: '1:90703966559:web:98ba3b527e6b7430af06ea',
    messagingSenderId: '90703966559',
    projectId: 'acutetriage-app',
    authDomain: 'acutetriage-app.firebaseapp.com',
    storageBucket: 'acutetriage-app.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcUjlubxHfjmAUT4o3fekghSeY3ZkqUaA',
    appId: '1:90703966559:web:558668ac15b117eeaf06ea',
    messagingSenderId: '90703966559',
    projectId: 'acutetriage-app',
    authDomain: 'acutetriage-app.firebaseapp.com',
    storageBucket: 'acutetriage-app.appspot.com',
  );
}