// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint

import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart' show StandardJsonPlugin;
import 'package:ferry_exec/ferry_exec.dart';
import 'package:flutter_starter/__generated__/schema.schema.gql.dart'
    show
        GAutoCompleteAddressInput,
        GCanChangeProfileFieldArg,
        GCandidateStatsInput,
        GCreatePlaceInput,
        GDateTime,
        GDatingProfileInfoInput,
        GDeleteProfileInput,
        GEditPlaceInput,
        GFeedbackType,
        GGetSuspensionsInput,
        GJSON,
        GLogoutInput,
        GNotificationOptionInput,
        GPhotoTestStatus,
        GPlaceSuggestionInput,
        GPollUserData,
        GProfileContactInformationInput,
        GProfileInfoInput,
        GRefreshAuthTokensInput,
        GReportInput,
        GReportType,
        GRevokeSuspensionInput,
        GSaveDeviceInfoArgs,
        GSendMessageInput,
        GShareProfileInput,
        GStartPhotoTestInput,
        GSuspensionInput,
        GUserFeedbackInput,
        GWhitelistPhoneNumberInput,
        GappFeature,
        GcandidateStatsType,
        GchatUserStatus,
        GcomplimentType,
        GconsumableItemTrigger,
        GconsumableItemType,
        Gfilter,
        Ggender,
        GinboxPreference,
        GinviteResponse,
        GlikedMeType,
        Glocales,
        GmessageAttachmentKind,
        GpollUserRelation,
        GpremiumEntitlement,
        Gregion,
        GrestrictedProfileField;
import 'package:gql_code_builder/src/serializers/operation_serializer.dart'
    show OperationSerializer;

part 'serializers.gql.g.dart';

final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..addPlugin(StandardJsonPlugin());
@SerializersFor([
  GAutoCompleteAddressInput,
  GCanChangeProfileFieldArg,
  GCandidateStatsInput,
  GCreatePlaceInput,
  GDateTime,
  GDatingProfileInfoInput,
  GDeleteProfileInput,
  GEditPlaceInput,
  GFeedbackType,
  GGetSuspensionsInput,
  GJSON,
  GLogoutInput,
  GNotificationOptionInput,
  GPhotoTestStatus,
  GPlaceSuggestionInput,
  GPollUserData,
  GProfileContactInformationInput,
  GProfileInfoInput,
  GRefreshAuthTokensInput,
  GReportInput,
  GReportType,
  GRevokeSuspensionInput,
  GSaveDeviceInfoArgs,
  GSendMessageInput,
  GShareProfileInput,
  GStartPhotoTestInput,
  GSuspensionInput,
  GUserFeedbackInput,
  GWhitelistPhoneNumberInput,
  GappFeature,
  GcandidateStatsType,
  GchatUserStatus,
  GcomplimentType,
  GconsumableItemTrigger,
  GconsumableItemType,
  Gfilter,
  Ggender,
  GinboxPreference,
  GinviteResponse,
  GlikedMeType,
  Glocales,
  GmessageAttachmentKind,
  GpollUserRelation,
  GpremiumEntitlement,
  Gregion,
  GrestrictedProfileField,
])
final Serializers serializers = _serializersBuilder.build();
